### ISSUE TITLE
Windows and Linux cross-platform builds and releases

### ISSUE THREAD

**Issue by NEXUS2345** [ChipsandCheese/CnC_GUI#1]
Enable cross-platform builds and releases for both Windows and Linux for the GUI

@Nintonito could you please comment with some details on what is left to do on this?

## TO DO

- [ ] Ship Linux build using .tar.gz with execute permissions on binaries
- [x] Update readme with instructions for installing dependencies on Linux
- [x] Fix relative path issues for Linux (@serebit)

**Comment by maxhaton** [comment]
Note that cross-platform when it comes to Linux is much more subtle than windows since you have to deal with distro conventions like the libc and so on

**Comment by Nintonito** [comment]
For this release, we are still doing the builds manual, but more platforms are included this time.  After this release we can talk in more depth about changes to make a proper build machine somewhere.

**Comment by NEXUS2345** [comment]
Releases including pre-compiled binaries for Linux are being delayed till the Flatpak package is created. This is because the installation of the Qt 6 libraries is exceedingly complex. Please see #13 for more details.
