### ISSUE TITLE
Debug mode for GUI

### ISSUE THREAD

**Issue by NEXUS2345** [ChipsandCheese/CnC_GUI#2]
It will aid future development and troubleshooting by adding a debug mode of some kind to the GUI that does not rely on debug tools found in IDEs or external tools. This is only going to be pretty basic to start with and print out values being executed to ensure that things like paths and file permissions are being set correctly.

**Comment by Nintonito** [comment]
Max merged changes that provide a more detailed debug output through the appropriate interface.  Closing this as the current scope for debug has been adequately met.
